### ISSUE TITLE
Feature Request: Compatibility with ListenBrainz

### ISSUE THREAD

**Issue by viasux** [RuiNtD/lastfm-rp#35]
I'm not sure if this is in the scope of the project, or if it would be a different project entirely, but support for using listenbrainz instead of last.fm would be nice.
https://listenbrainz.org

**Comment by RuiNtD** [comment]
I've added support for ListenBrainz. Just change `provider` in your config from `lastfm` to `listenbrainz`. I may add support for a local ListenBrainz server in the future and I'll probably be tweaking the assets in the next few days.

![image](https://github.com/user-attachments/assets/255e2c76-3507-47a8-b888-03e338024c5d)
![image](https://github.com/user-attachments/assets/e0a2f8e8-a89d-4cb1-9061-a9590b777b76)

**Comment by viasux** [comment]
> I've added support for ListenBrainz. Just change `provider` in your config from `lastfm` to `listenbrainz`. I may add support for a local ListenBrainz server in the future and I'll probably be tweaking the assets in the next few days.
> 
> ![image](https://private-user-images.githubusercontent.com/1149870/369181928-255e2c76-3507-47a8-b888-03e338024c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDAyNzUsIm5iZiI6MTcyNzQ5OTk3NSwicGF0aCI6Ii8xMTQ5ODcwLzM2OTE4MTkyOC0yNTVlMmM3Ni0zNTA3LTQ3YTgtYjg4OC0wM2UzMzgwMjRjNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDUwNjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmEwOTA1ZDMzY2JhNDRkMzkzOGFiOTQ3ZjZkNjBiOTEwNTFlOWM5ZWM3ZmZhNjljZDcxNTVjMjU0ZmI4MDg4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0TfcsAe09vOD9MUosds5VhoaB8Gecgt1k8MTS-hcXE8) ![image](https://private-user-images.githubusercontent.com/1149870/369174624-e0a2f8e8-a89d-4cb1-9061-a9590b777b76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDAyNzUsIm5iZiI6MTcyNzQ5OTk3NSwicGF0aCI6Ii8xMTQ5ODcwLzM2OTE3NDYyNC1lMGEyZjhlOC1hODlkLTRjYjEtOTA2MS1hOTU5MGI3NzdiNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDUwNjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY2NWQwNTg5MDg3OWE4ZGQzY2JhNTVhYjM5Y2NlZTQ0OTdjN2RhNGQyMjE4OWVjZmMxN2RmNmU3MjNjMzg1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OkCCL8yhQxpumqo_I-vyhT_-JjsdecexRwUKZHdkvoo)

is it possible to connect to both? like connect to lastfm and listenbrainz at the same time

**Comment by RuiNtD** [comment]
What's the point of that? If you have both, ideally you'd be scrobbling to both and it wouldn't matter at that point which you use.

**Comment by viasux** [comment]
Oh, I forgot you can connect listenbrainz to lastfm lol :)

**Comment by viasux** [comment]
> What's the point of that? If you have both, ideally you'd be scrobbling to both and it wouldn't matter at that point which you use.

I just realized I thought this was a different repository LOL ignore my previous comment im having a night 💀
